pool:
  name: Elanthamilan  

jobs:
- job: RunPowerShellScript
  displayName: 'Run PowerShell Script'
  steps:
  - task: AzurePowerShell@5
    inputs:
      azureSubscription: 'keyvault-fl'
      ScriptType: 'InlineScript'
      Inline: |
        $keyVaultName = "keyvault-fl-k"
        $username = "sql-user11"
        
        $password = -join ((65..90 + 97..122 + 48..57 + 33 + 35..38 + 42 + 64 + 95) | Get-Random -Count 12 | ForEach-Object {[char]$_})
        
        Write-Host "$password"
        
        $securepassword = ConvertTo-SecureString $password -AsPlainText -Force
        
      azurePowerShellVersion: 'LatestVersion'
    displayName: 'Run PowerShell Script'

- job: AnotherJob
  displayName: 'Another Job'
  dependsOn: RunPowerShellScript
  steps:
  - script: echo "This is Another Job"
    displayName: 'Run Another Job'
